alasql('SELECT * FROM SECCIONES S JOIN DATOS_LEGALES D ON S.ID_CONTRATO = D.FOLIO WHERE D.FOLIO=? AND (D.BANDERA_COMENT_LEGALES  = "true" OR D.BANDERA_COMENT_FZ="true" OR D.BANDERA_COMENT_SEG="true" OR (S.BANDERA_COMENTARIOS= "true" AND S.TITULO LIKE "%R3SPONS4BL3%"))',("FU0000005")) 

alasql('SELECT * FROM SECCIONES S JOIN REGISTROS R ON S.ID_CONTRATO = R.FOLIO WHERE R.FOLIO=? AND (R.BANDERA_COMENT_DATOS  = "true" OR R.BANDERA_COMENTARIOS_ANEXOS="true" OR (S.BANDERA_COMENTARIOS= "true" AND S.TITULO NOT LIKE "%R3SPONS4BL3%"))',("FU0000005")) 

